name: DevOps Accelerate Worflow Task

on: [push]

jobs:
  Show-OS-Name-And-Other-Details:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: List files in the repository
      - run: ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."
    
