name: DevOps Accelerate Worflow Task

on: [push]

jobs:
  Show-OS-Name-And-Other-Details:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
      - run: ls ${{ github.workspace }}
      
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open for a day with no activity.'
        close-issue-message: 'This issue was closed because it has been stalled for 2 days with no activity.'
        stale-issue-label: 'no-issue-activity'
        days-before-issue-stale: 1
        days-before-issue-close: 2
    
